modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Cortex"
description='''
Far distance rendering mod utilising LoDs.
'''
logoFile="assets/voxy/icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sodium"
type="required"
versionRange="[0.6.13,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="client.voxy.mixins.json"

[[mixins]]
config="common.voxy.mixins.json"
